# Generated by Django 4.2.1 on 2023-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
