# Generated by Django 4.2.1 on 2023-05-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0004_friendrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Дружба', 'verbose_name_plural': 'Дружба'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Заявка в друзья', 'verbose_name_plural': 'Заявки в друзья'},
        ),
    ]
